BN254 and Grumpkin Poseidon configurations
privacy-scaling-explorations/sonobe pull request #106
Opened 2024-05-29 15:56 UTC by ax0

This PR resolves #85 by including Poseidon configurations for the scalar fields of the BN254 and Grumpkin curves. The former configuration agrees with Circom's Poseidon(4) and the latter was generated using the reference implementation script. For all other fields, the configuration falls back to the test configuration used previously. Tests have been modified to use this curve cycle.

2024-05-30 08:54 UTC, arnaucube approved these changes
Great!! ^^

2024-05-31 14:26 UTC, dmpierre commented on folding-schemes/src/transcript/poseidon/grumpkin.rs
> +// https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/generate_params_poseidon.sage
Proposing to also add sage script's arguments to ease reproducibility. Checked on my side and correct me if I'm wrong, but should be those ones?

```suggestion
// https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/generate_params_poseidon.sage
// generated with `sage generate_params_poseidon.sage 1 0 254 5 5 128 0x30644e72e1
31a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47`
```

2024-05-31 14:27 UTC, dmpierre requested changes
Thanks for this!
Proposing to add a comment on the arguments used with sage when generating parameters.

2024-06-01 08:34 UTC, dmpierre approved these changes

2024-06-03 12:36 UTC, merged